based-kwl/SemesterPlanner-client

src/components/Authentication/SignIn.js
- added error message on sign in page for incorrect username or password (error code 401) or server response error message display otherwise
closes #44
=> merging sign in page error message display to main

src/App.js, src/components/CustomMUIComponents/CustomButtons.js, src/components/Profile/Mocks/mockUser.json, src/components/StudyRoom/Mocks/mockStudyRoom.json, src/components/StudyRoom/StudyRoom.js, src/components/StudyRoom/StudyRoomCreate.js, src/components/StudyRoom/StudyRoomHome.js, src/components/StudyRoom/StudyRoomSettings.js
Want to merge this user story with the other branch I am working on to complete the virtual room functionality.
Mock data was used since we are having issues with the back end. Once the back end is fixed I can update my functions. 
the settings page was implemented as it fetches study room data of the owner of the page. If you are not the owner, you are redirected to study room home page (in case you try to access typing the URL directly)
The update and delete functions are implemented but not functional as we are waiting for the backend
=> Sp 48 virtual room settings page

src/components/StudyRoom/ParticipantsList.js, src/components/StudyRoom/StudyRoom.js, src/components/StudyRoom/StudyRoomCards.js
Requesting merge of participants tab in study room chat to the study room chat branch
Closes #49
=> merging sp-49 participants tab into sp-47 study room chat

src/components/StudyRoom/BottomDrawer.js
merging bottom drawer fix into virtual study room branch (original branch in which bottom drawer was implemented)
Closes #57
=> Sp 57 bottom drawer fix

src/App.js, src/components/StudyRoom/StudyRoomCreate.js, src/components/StudyRoom/StudyRoomHome.js, src/components/StudyRoom/StudyRoomSettings.js
implemented endpoints for create,settings and homepage of the virtual room 
please use : user_3v5bi5s61v@gmail.com
I just tested it with this user and it should work
=> Axios virtual room

package.json, src/components/CustomMUIComponents/CustomButtons.js, src/components/StudyRoom/CourseNotes.js, src/components/StudyRoom/ParticipantsList.js, src/components/StudyRoom/StudyRoom.js, src/components/StudyRoom/StudyRoomCards.js, src/components/StudyRoom/StudyRoomSettings.js
=> Sp 50 course note tab merging into sp-47 to complete feature set

package-lock.json, src/App.js, src/components/StudyRoom/CourseNotes.js, src/components/StudyRoom/ParticipantsList.js, src/components/StudyRoom/StudyRoomChat/ChatFooter.js, src/components/StudyRoom/StudyRoomChat/StudyRoomChat.js, src/components/StudyRoom/StudyRoomHome.js, src/components/StudyRoom/StudyRoomSettings.js
merging frontend variable name refactor to main
Closes #86
=> Sp-86 updated var names frontend refactor

src/components/Calendar/Calendar.js, src/components/Calendar/Event/CreateEvent.js
- updated Calendar.js page to use drawers for 'add event' operations
- updated updateEventList(...) method in Calendar.js to allow event list state updates for new event additions
- removed redundant/unused prop being passed to EditEvent.js component from Calendar.js component
- tested updates to ensure correct functionality
Closes #99
=> [99] Update add event page to use drawers

src/components/Calendar/Custom/CommonInputEventForm.js, src/components/Calendar/Event/CreateEvent.js, src/components/CustomMUIComponents/CustomButtons.js
implemented the event types in order for us to gather statistics on the activities of students as well as extract information from the courses needed for the study aid epic
@jas let me know what needs to be done for testing
=> 101 add category type to event creation

package-lock.json, src/components/Calendar/Calendar.js, src/components/Calendar/Custom/CommonInputEventForm.js, src/components/Calendar/Event/CreateEvent.js, src/components/Calendar/ImageUpload.js
This PR implements event creation using an uploaded image.
Closes #102 
Test images used are shown below:
=> Sp 21 camera based event creation 2

src/components/Calendar/Custom/CommonInputEventForm.js, src/components/Calendar/Event/CreateEvent.js, src/components/Calendar/Event/EditEvent.js
added the course list for the student type. Needed that functionality for #27 
fixed the layout problem (for both add and edit events) where the primarybuttons2 would disappear from the page when there was an overflow
which is related to issue #98
=> [116] Study type refactoring relates to SP-27

src/components/Calendar/Calendar.js, src/components/CustomMUIComponents/CustomCards.js
- added responsiveness to the Calendar.js
=> [#117][UI-Enhancement]

package-lock.json, package.json, src/App.js
- added hotjar to preliminary testing
=> [#138][Usability Testing] Hotjar

src/components/Calendar/Calendar.js, src/components/Calendar/CommonFunctions.js, src/components/Calendar/Custom/CommonInputEventForm.js, src/components/Calendar/Event/CreateEvent.js, src/components/Calendar/calendar.css
This PR fixes issue #69:
- implemented daily recurring event expansion on user event fetching
- implemented weekly recurring event expansion on user event fetching
- implemented monthly recurring event expansion on user event fetching
- implemented method for event list sorting by date
- fixed default recurrence switch and type states when editing an event
- refactored CreateEvent.js to use CommonInputEventForm.js elements to remove duplicate code between components
=> [#135][bugfix] Recurring Events Display Fix

src/components/Calendar/CommonFunctions.js, src/components/ProgressReports/fetchingCategoryDataFactory.js
- removed event list expansion from statistics, as it is now being handled in the backend
=> [#140][Bugfix] Study Statistics do not always take recurrent events into account

cypress/support/commands.js, src/components/Authentication/Authentification.js, src/components/Authentication/SignIn.js, src/components/Calendar/Calendar.js, src/components/Calendar/Custom/CommonInputEventForm.js, src/components/Calendar/Event/CreateEvent.js, src/components/Calendar/Event/EditEvent.js, src/components/Calendar/Event/ScheduleEvent.js, src/components/FriendList/FriendListHome.js, src/components/FriendList/FriendSearch.js, src/components/FriendList/FriendsNotification.js, src/components/NavDrawer/NotificationMenu.js, src/components/NavDrawer/navDrawer.js, src/components/Profile/EditProfile.js, src/components/ProgressReports/ProgressReportHome.js, src/components/ProgressReports/StudyRecap.js, src/components/ProgressReports/fetchingCategoryDataFactory.js, src/components/StudyRoom/ParticipantsList.js, src/components/StudyRoom/StudyRoomChat/ChatFooter.js, src/components/StudyRoom/StudyRoomChat/StudyRoomChat.js, src/index.js
- moved token storage from localStorage to cookie with httpOnly access to mitigate possibility of XSS attacks
- token cookie is now sent to backend along with all requests made
- implemented logout route request to backend (used for backend to instruct frontend to delete the jwt cookie on logout)
- implemented automatic user logging out and redirection to login page on token expiration
Closes guaj/SemesterPlanner-Server#74
Closes #89
=> [144][Security] User token route verification

src/components/StudyRoom/StudyRoomCreate.js, src/components/StudyRoom/StudyRoomHome.js
Fixed the create button that would move outside the window for large windows
also added a title to study group homepage for consistency
=> [148][BUGFIX] button disappears with window size change

src/components/Calendar/Calendar.js, src/components/ProgressReports/ProgressReportHome.js
Updated progress report page's UI
=> [152][UI enhancement fix] progress report homepage

src/components/Calendar/Calendar.js, src/components/Profile/EditProfile.js, src/components/ProgressReports/ProgressReportHome.js
disabled the username field so that users are not allowed to update and loose the events associated to their username
=> [154][BUG FIX] disable username edit

src/components/Authentication/SignIn.js, src/components/Calendar/Event/EditEvent.js, src/components/Calendar/EventColorSelector/EventColorDisplay.js, src/components/Calendar/EventColorSelector/EventColorSelector.js, src/components/Calendar/calendar.css, src/components/CustomMUIComponents/CustomButtons.js, src/components/StudyRoom/StudyRoomCreate.js, src/components/StudyRoom/StudyRoomHome.js, src/components/StudyRoom/StudyRoomSettings.js
- removed commented code in SignIn.js removed duplicate import in EditEvent.js
- removed unused imports in EventColorDisplay.js
- removed unused function in EventColorSelector.js
- Removed all minor issues from SonarCloud
=> [CodeSmell] Cleanup

src/components/NavDrawer/NotificationMenu.js, src/components/NavDrawer/examNotification.js, src/components/NavDrawer/examNotificationFactory.js
this PR implements the time slot events in the Exam Notification drawer.
=> [#30] [PR] exam study planning -time slot implementation 

package-lock.json, package.json, src/components/Authentication/SignUp.js, src/components/Calendar/Calendar.js, src/components/StudyRoom/StudyRoomCreate.js, src/components/StudyRoom/StudyRoomHome.js, src/index.js
- added different styled scroll bar for study room list
- redirected user to calendar after new user creation instead of redirecting to the login screen
- fixed a bug where entering incorrect login credentials reloaded the login page instead of displaying the "incorrect username/password" error message
- modified study room creation code to include study room owner as the first user in the participants list
=> [167] User creation process enhancement
